server:
port : 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB # 파일의 용량 제한
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  config:
    import: optional:file:.env[.properties]

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
cloud:
  aws:
    s3:
      servlet:
        multipart:
          max-file-size: 10MB  # 업로드 가능한 파일 크기
          max-request-size: 10MB
      bucket: daruda
    credentials:
      access-key: ${S3ACCESSKEY}
      secret-key: ${S3SECRETKEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  file:
    path: ./daruda_log
  level:
    org.springframework.web: DEBUG
    org.hibernate.type: DEBUG
  config: classpath:logback-spring.xml

kakao:
  client_id: ${CLIENT_ID}
  redirect_uri: ${REDIRECT_URI}

jwt:
  secret: ${JWT_SECRET}
  access-token-expire-time: ${ACCESS_TOKEN_EXPIRE_TIME}
  refresh-token-expire-time: ${REFRESH_TOKEN_EXPIRE_TIME}


