server:
port: 8080

spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  elasticsearch:
    uris: localhost:9200
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
cloud:
  aws:
    s3:
      servlet:
        multipart:
          max-file-size: 10MB  # 업로드 가능한 파일 크기
          max-request-size: 10MB
      bucket: daruda
    credentials:
      access-key: ENC(zUS78/F8P/qh/KpSGK/GV3vjanLZSodMm0O1b0JKuno=)
      secret-key: ENC(9o72B0yxr1Mx4LpLpqoWdgIFhCt9/zhMy0FzGKmEaxxF7cuzI/ZvxmH685+s0xd+8YbC9HRRhjU=)
    region: ap-northeast-2
    stack:
      auto: false

logging:
  file:
    path: ./daruda_log
  level:
    org.springframework.web: DEBUG
    org.hibernate.type: DEBUG
  config: classpath:logback-spring.xml

kakao:
  client_id: 65b8edb9273b17a701f937868170f95e
  redirect_uri: http://localhost:5173/api/v1/users/kakao/login-url

jwt:
  secret: ${JWT_SECRET}
  access-token-expire-time: 12000000
  refresh-token-expire-time: 604800000


